### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [TiMaTiFeY/ScreenRemoteControlApp#1]
1. Сделайте всё-таки так, как я Вам предлагал: пусть при подключении каждый клиент первым сообщением шлёт свой тип (экран, мышь, клавиатура), а сервер в соответствии с этим типом будет создавать нужный sender или receiver. Это даст Вам сразу несколько преимуществ:
    1. Вы сможете использовать только один порт на сервере (при этом на поток данных будет свой клиент-сокет)
    1. Вы сможете легко настраивать, какие возможности будет использовать клиент (например, только смотреть экран без передачи мыши и клавиатуры) просто подключаясь или не подключаясь соответствующим клиентом. Сейчас это не так просто, ведь сервер ждёт определённое количество соединений.
    1. Это автоматически даст Вам сервер, который не нужно перезапускать, чтобы снова подключиться.
    1. Кроме того, это позволит подключиться к серверу любому числу клиентов одновременно (если только Вы там где-нибудь не завязывались на единственность каждого обработчика, но я вроде такого не увидел).
1. Сделайте так, чтобы gradle собирал jar, причём с зависимостями, чтобы не нужно было собирать проект на каждом компьютере, на котором его нужно запустить.
1. Было бы неплохо добавить для сервера консольный режим. То есть, чтобы при задании нужных аргументов командной строки, сразу запускался сервер на нужном порту, это позволит удалённо его запустить без доступа к экрану (чтобы доступ к экрану получить).

**Comment by timatifey** [comment]
1. Вроде сделал
2. Добавил в gradle сборку в uber-jar
3. Добавил, что если при запуске есть аргумент порта (-p), то графическое  окно не запускается, но запускается сервер на данном порту
